---
title: "Conditionals Loops"
author: "Halina Do-Linh"
date: "8/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Task 1
```{r}
pm2_5 <- 100

if (pm2_5 < 100) {
  print("Low to moderate risk")
} else if (pm2_5 <= 100 & pm2_5 < 150) {
  print("Unhealthy for sensitive groups")
} else if (pm2_5 >= 150) {
  print("Health risk present")
}

# my error here was that I did not use the "else if" in the second condition, only used "else". Try to recall what this error message means

```

## Task 2
```{r}
species <- "blue_whale"

if (str_detect(species, "whale")) {
  print("Whales are the best")
}

# changed blue_whale to blue_bird and my output was nothing, yay!

```

## Task 3 
```{r}
max_airtemp_c <- 50

if (max_airtemp_c > 27) {
  print("Temperature too high")
} else if (max_airtemp_c <= 27) {
  print("Temperature OK")
}

# changed air temp from 24.1 to 50 and it worked, yay!

```
## Task 4 
```{r}
base_burrito <- 6.50
main_ingredient <- c("veggie", "chicken", "steak")

if (str_detect(main_ingredient, "veggie")) {
  print(base_burrito)
} if (str_detect(main_ingredient, "chicken")) {
  print(base_burrito + 3)
} if (str_detect(main_ingredient, "steak")) {
  print(base_burrito + 3.25)
}

# come back to this task later

```
## Task 4
```{r}
fish <- c(8, 10, 12, 23)
sum_fish <- sum(fish)
sum_fish

# proportion is fish type / 53

proportion_fish <- vector(mode = "numeric", length = length(fish))

for (i in seq_along(fish)) {
  proportion_val <- (fish / sum_fish)
  proportion_fish <- proportion_val
}

proportion_fish

# for iterating and having the fish names come out

# fish_names <- c("goldfish", "tetras", "guppies", "mollies")

#for (i in seq_along(fish)) {
#  proportion_val <- fish[i] / sum(fish)
#  proportion_fish <- proportion_val
#  print(paste(fish_names[i]), proportion_fish)
# }

```

## Task 6 
```{r}
month.name <- month.name

for (i in seq_along(month.name)) {
  print(month.name[i])
}

```



