---
title: "Task 7 Real Data"
author: "Halina Do-Linh"
date: "8/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
```

## Task 7
```{r}
toolik_biochem <- read_csv(here::here("data", "2011_Kling_Akchem.csv"), na = ".") %>% 
  janitor::clean_names()

```

## Create a subset
```{r}
inlet_biochem <- toolik_biochem %>% 
  filter(site == "Toolik Inlet") %>% 
  select(p_h, doc_u_m, tdn_u_m)

```

## Find the mean 3 different ways
```{r}
# the long way using a for loop
mean_inlet_biochem <- vector(mode = "numeric", length = ncol(inlet_biochem))
                             
for (i in 1:ncol(inlet_biochem)) {
  mean_val <- mean(inlet_biochem[[i]], na.rm = TRUE)
  mean_inlet_biochem[i] <- mean_val
}

mean_inlet_biochem
# remember that [] the output will be container and its contents, and with [[]] is will only be the contents, or values.  

# find mean using apply()
apply(X = inlet_biochem, 2, mean, na.rm = TRUE)

# 2 means columns 
# 1 means rows

# find mean using purrr::map_df()
purrr::map_df(.x = inlet_biochem, .f = mean, na.rm = TRUE)

```

